apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: doctor-office
spec:
  replicas: 2  # Number of pod replicas for scalability and availability
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hemanthkolli99/backend:latest  # Docker Hub image URL
        ports:
        - containerPort: 3000  # Port where the backend service runs inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP  # Internal service, accessible only within the Kubernetes cluster
